### PR TITLE
updated to run with more recent version of python packages

### PR DESCRIPTION
**Pull request by jtapolcai**
Minor changes only to run with the latest networkx and pyglet packages

### CODE REVIEW

**Comment by frapa** [comment]
@jtapolcai Thanks for the contribution. Did you test this in python 2 or 3?

**Comment by jtapolcai** [comment]
I have modified them according to the python package documentations, e.g. they write in NetworkX 2.0 G.edges_iter() has been removed.  I have tested it only for Python 3.

**Comment by jtapolcai** [comment]
One more issue for python 3.x : the .iteritems() should be replaced with .items() everywhere in the code.

**Comment by frapa** [comment]
Thanks, I merge this. It would be very cool if you could make a PR also for the `.iteritems() -> .item()` for python 3 support. I would just drop python 2 support...

**Pull request merged**
